name: Kumona Vision Care API CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: kumona_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Generate Prisma Client
        run: npx prisma generate
        
      - name: Create .env file
        run: |
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/kumona_test?schema=public" > .env
          echo "JWT_SECRET=test-secret-key" >> .env
          
      - name: Run migrations
        run: npx prisma migrate deploy
        
      - name: Run tests
        run: npm test
        
      - name: Run e2e tests
        run: npm run test:e2e

  build:
    name: Build and Deploy
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/kumona-api:latest,${{ secrets.DOCKER_HUB_USERNAME }}/kumona-api:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/kumona-api:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/kumona-api:buildcache,mode=max
          
      # Exemplo de deploy para Koyeb (pode ser adaptado para outros provedores)
      - name: Deploy to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: kumona-api
          service-name: api
          git-branch: main
          api-token: ${{ secrets.KOYEB_API_TOKEN }}
